{lib}:
{
  username = "songlin";
  userfullname = "Songlin Bai";
  useremail = "songlin2610@outlook.com";
  networking = import ./networking.nix {inherit lib;};
  # generated by `mkpasswd`
  initialHashedPassword = "$y$j9T$68il26tDlQQ1iGRdsZqav/$68sac0/2ZXwFH3RtJSJ5f.KDAUfjmjd1eKDm/iF933D";
  # Public Keys that can login to all device
  # generate by `ssh-keygen -t ed25519 -a 256 -C "songlin@xxx" -f ~/.ssh/xxx`
  sshAuthorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIECHbH9e7atn30ZeCfGqyocWrd2lN5JjDm2MpY0yglVU songlin@mbp"
  ];
}

